### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by ChillarAnand** [appknox/irene#382]
```
const instrumentation = require('../utilities/instrumentation');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/chillaranand/.nodeenvs/irene/lib/node_modules/ember-cli/bin/ember:24:11
    at /home/chillaranand/.nodeenvs/irene/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:45:21
    at ondir (/home/chillaranand/.nodeenvs/irene/lib/node_modules/ember-cli/node_modules/resolve/lib/async.js:196:
```

**Comment by jagamts1** [comment]
updating node js will solve this problem.http://stackoverflow.com/questions/36789889/syntaxerror-use-of-const-in-strict-mode

**Comment by ChillarAnand** [comment]
Thanks @jagamts1. Fixed it in https://github.com/appknox/irene/pull/403
